name: Build APK

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Generate .env
        run: |
          echo "SUPABASE_URL=https://rhveqvlldliccalfsuea.supabase.co" >> .env
          echo "SUPABASE_ANON_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJodmVxdmxsZGxpY2NhbGZzdWVhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODExMjg5MjMsImV4cCI6MjA5NjcwNDkyM30.NrsH1optDK2IbOl8YUqBwUZaidvEk72lvrA4SEHPrVY" >> .env
          echo "LIVEKIT_URL=wss://welber-s7yegwse.livekit.cloud" >> .env

      - name: Get dependencies
        run: flutter pub get

      - name: Build Debug APK (Generates Keystore)
        run: flutter build apk --debug

      - name: Build APK
        run: flutter build apk --release -v

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: colow-apk
          path: build/app/outputs/flutter-apk/app-release.apk
